### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Montaxx** [stunna/xbmc-addon-wilmaa#2]
any updates on this?

**Comment by stunna** [comment]
thx, will add this, as soon as i can test it

**Comment by Nexolight** [comment]
For me it works until I try to open a channel. The channels are shown correctly but they just don't play. I think this is because of missing credidentials which I can not enter because Kodi says "This plugin can't be configured"

**Comment by bruno-briner** [comment]
Hi.

Is this addon still working?

Thanks!

Bruno

**Comment by stunna** [comment]
no, not tested with newer versions

**Comment by stunna** [comment]
not working, no additions
